apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: whoami
  name: whoami
  namespace: demo-02
spec:
  externalName: whoami.demo-01.svc.cluster.local
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami
  type: ExternalName
status:
  loadBalancer: {}
