apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: obo-web
  name: obo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obo-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: obo-web
    spec:
      volumes:
      - name: web-config
        configMap:
          name: obo-web-config
      containers:
      - image: public.ecr.aws/i0z2b2w3/obo-web:1.1
        name: obo-web
        resources: {}
        volumeMounts:
        - name: web-config
          mountPath: /techmaster-obo-web/src/main/resources/application-dev.properties
          subPath: application-dev.properties
status: {}
